name: Build Report PDF

on:
  push:
    paths:
      - "report/Report.tex"
      - ".github/workflows/build_pdf.yml"
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install LaTeX
        uses: dante-ev/latex-action@v2
        with:
          working_directory: report
          root_file: Report.tex

      - name: Upload PDF Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Report_PDF
          path: report/Report.pdf
